# Generated by Django 5.0.2 on 2024-02-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0003_alter_employee_contact_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='contact_No',
            field=models.IntegerField(default=0),
        ),
    ]
